# syntax=docker/dockerfile:1
#FROM python:3.11.0-slim-buster
FROM python:3.11-slim-bookworm
WORKDIR /source
ENV WORKDIR=/source
ENV XY
COPY ./ /source
RUN pip3 install -r /source/requirements.txt
CMD ["xxx", "run"]
